import { Hono } from "hono";

export const termsRoutes = new Hono();

const LAST_UPDATED = "March 6, 2026";

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service — Cliphy</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.8; max-width: 680px; margin: 0 auto; padding: 3rem 1.5rem; font-size: 15px; -webkit-font-smoothing: antialiased; }
    h1 { font-size: 1.75rem; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 0.25rem; }
    .updated { color: #6b7280; font-size: 0.85rem; margin-bottom: 2.5rem; }
    h2 { font-size: 1.1rem; font-weight: 600; margin-top: 2.5rem; margin-bottom: 0.75rem; letter-spacing: -0.01em; }
    p { margin-bottom: 1rem; color: #374151; }
    li { margin-bottom: 0.5rem; color: #374151; }
    ul { padding-left: 1.25rem; margin-bottom: 1rem; }
    a { color: #4f46e5; text-decoration: none; }
    a:hover { text-decoration: underline; }
    strong { font-weight: 600; color: #1a1a1a; }
    .footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.8rem; }
  </style>
</head>
<body>
  <h1>Terms of Service</h1>
  <p class="updated">Last updated: ${LAST_UPDATED}</p>

  <p>These Terms of Service ("Terms") govern your use of the Cliphy Chrome extension and related services ("Service") operated by Cliphy ("we", "us", "our"). By using Cliphy, you agree to these Terms.</p>

  <h2>1. Description of Service</h2>
  <p>Cliphy is a Chrome extension that generates AI-powered summaries of YouTube videos. The Service includes a free tier with limited usage and a paid Pro tier with expanded limits and features.</p>

  <h2>2. Account &amp; Eligibility</h2>
  <ul>
    <li>You must sign in with a Google account to use Cliphy.</li>
    <li>You must be at least 13 years old (or 16 in the EEA) to use the Service.</li>
    <li>You are responsible for all activity under your account.</li>
    <li>One account per person. Automated or bulk account creation is not permitted.</li>
  </ul>

  <h2>3. Acceptable Use</h2>
  <p>You agree not to:</p>
  <ul>
    <li>Use the Service to violate any laws or third-party rights.</li>
    <li>Attempt to circumvent usage limits, rate limiting, or access controls.</li>
    <li>Reverse engineer, scrape, or abuse the API.</li>
    <li>Use automated tools to interact with the Service beyond normal extension usage.</li>
    <li>Resell or redistribute summaries generated by the Service for commercial purposes.</li>
  </ul>

  <h2>4. Subscriptions &amp; Billing</h2>
  <ul>
    <li>The Pro plan is billed monthly via Stripe. Prices are displayed at checkout.</li>
    <li>Subscriptions renew automatically unless cancelled before the next billing date.</li>
    <li>You can cancel anytime through the Manage Subscription option in the extension. Cancellation takes effect at the end of the current billing period.</li>
    <li>We do not offer refunds for partial billing periods. If you believe you were charged in error, contact us.</li>
    <li>We reserve the right to change pricing with 30 days' notice. Existing subscribers will be notified before any price change takes effect.</li>
  </ul>

  <h2>5. Free Tier</h2>
  <ul>
    <li>Free accounts have a monthly summary limit and a 7-day summary retention period.</li>
    <li>We may adjust free tier limits at any time.</li>
  </ul>

  <h2>6. AI-Generated Content</h2>
  <ul>
    <li>Summaries are generated by AI (Anthropic's Claude) and may contain inaccuracies, omissions, or errors.</li>
    <li>Summaries are provided for informational purposes only and should not be relied upon as a substitute for watching the original video.</li>
    <li>We do not guarantee the accuracy, completeness, or quality of any summary.</li>
  </ul>

  <h2>7. Intellectual Property</h2>
  <ul>
    <li>Cliphy and its original content, features, and functionality are owned by us and protected by applicable intellectual property laws.</li>
    <li>Summaries generated from YouTube videos are derivative of the original content. Your use of summaries must comply with YouTube's Terms of Service.</li>
    <li>You retain no ownership rights over AI-generated summaries beyond personal, non-commercial use.</li>
  </ul>

  <h2>8. YouTube Content</h2>
  <p>Cliphy accesses publicly available YouTube video transcripts. We are not affiliated with, endorsed by, or sponsored by YouTube or Google. Your use of YouTube content through Cliphy is subject to <a href="https://www.youtube.com/t/terms">YouTube's Terms of Service</a>.</p>

  <h2>9. Service Availability</h2>
  <ul>
    <li>We strive to keep Cliphy available but do not guarantee uninterrupted service.</li>
    <li>We may modify, suspend, or discontinue any part of the Service at any time.</li>
    <li>Summaries depend on transcript availability. Not all YouTube videos have transcripts.</li>
  </ul>

  <h2>10. Limitation of Liability</h2>
  <p>To the maximum extent permitted by law, Cliphy is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</p>
  <p>Our total liability for any claim related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim, or $50, whichever is greater.</p>

  <h2>11. Account Termination</h2>
  <ul>
    <li>You may stop using Cliphy at any time by uninstalling the extension and cancelling your subscription.</li>
    <li>We may suspend or terminate your account if you violate these Terms.</li>
    <li>Upon termination, your right to use the Service ceases immediately. We may delete your data in accordance with our <a href="/privacy">Privacy Policy</a>.</li>
  </ul>

  <h2>12. Changes to Terms</h2>
  <p>We may update these Terms from time to time. If we make material changes, we will notify you via the extension or by email. Continued use of Cliphy after changes constitutes acceptance of the updated Terms.</p>

  <h2>13. Governing Law</h2>
  <p>These Terms are governed by the laws of the United States. Any disputes shall be resolved in the courts of the United States.</p>

  <h2>14. Contact</h2>
  <p>For questions about these Terms:</p>
  <p><a href="mailto:cliphy.ai+support@gmail.com">cliphy.ai+support@gmail.com</a></p>

  <div class="footer">
    <p>&copy; 2026 Cliphy. All rights reserved.</p>
  </div>
</body>
</html>`;

termsRoutes.get("/", (c) => {
  return c.html(html);
});
